#index:
#    path: /
#    controller: App\Controller\DefaultController::index

guide :
  resource: routes/guide/routes.yaml
  prefix: /guideMichelin

#guide_accueil:
#  path: /accueil
#  controller: App\Controller\GuideController::accueil