guide_accueil:
  path: /accueil
  controller: App\Controller\GuideController::accueil

guide_menu:
  path: /menu
  controller: App\Controller\GuideController::menu

guide_restaurants:
  path: /restaurants
  controller: App\Controller\GuideController::restaurants

guide_chefs:
  path: /chefs
  controller: App\Controller\GuideController::chefs

guide_plats:
  path: /plats
  controller: App\Controller\GuideController::plats

restaurant_voir:
  path: /restaurant/voir/{id}
  controller: App\Controller\GuideController::voir
  requirements:
    numero: \d+

restaurant_modifier:
  path: /restaurant/modifier/{id}
  controller: App\Controller\GuideController::modifier
  requirements:
    id: \d+